# Generated by Django 3.2.23 on 2023-11-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20231127_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='team_invite_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
