# Generated by Django 3.2.23 on 2023-12-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20231204_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='specific_day_of_month',
        ),
        migrations.AlterField(
            model_name='habit',
            name='specific_days_of_week',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50, null=True),
        ),
    ]
