# Generated by Django 3.2.23 on 2023-12-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20231204_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
