# Generated by Django 3.2.23 on 2023-12-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20231204_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='habit',
            name='specific_days_of_week',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
