# Generated by Django 3.2.23 on 2023-12-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20231217_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lang',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
