# Generated by Django 3.2.23 on 2023-12-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_customuser_expo_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborativelist',
            name='dateline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notifications',
            field=models.BooleanField(default=False),
        ),
    ]
