# Generated by Django 3.2.23 on 2024-01-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20240111_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
