# Generated by Django 3.2.23 on 2024-01-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_notes_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
