# Generated by Django 3.2.23 on 2024-02-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_notes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='habitidentifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='member1sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='member2sync',
            field=models.BooleanField(default=False),
        ),
    ]
