# Generated by Django 3.2.23 on 2024-02-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20240204_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='member1sync',
            new_name='ismember1sync',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='member2sync',
            new_name='ismember2sync',
        ),
    ]
