# Generated by Django 3.2.23 on 2024-02-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20240206_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
