# Generated by Django 3.2.23 on 2024-02-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_habit_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='specific_day_of_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
