# Generated by Django 3.2.23 on 2024-02-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_habit_specific_day_of_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='specific_day_of_month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
