# Generated by Django 3.2.23 on 2024-03-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20240314_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='productid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
