# Generated by Django 3.2.23 on 2024-09-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20240401_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_status_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
