# Generated by Django 3.2.23 on 2024-09-06 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_item_last_status_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_points', models.IntegerField(default=0)),
                ('habits_points', models.IntegerField(default=0)),
                ('list_points', models.IntegerField(default=0)),
                ('notes_points', models.IntegerField(default=0)),
                ('event_points', models.IntegerField(default=0)),
                ('leaderboard_position', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
