# Generated by Django 3.2.23 on 2024-09-16 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_team_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('author_name', models.CharField(max_length=255)),
                ('author_profile_pic', models.ImageField(default='default_profile_pic.png', upload_to='author_pics/')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('color', models.CharField(default='white', max_length=10)),
                ('quiz', models.JSONField(blank=True, default=dict)),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
