# Generated by Django 3.2.23 on 2024-09-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.JSONField(default=dict),
        ),
    ]
