# Generated by Django 3.2.23 on 2024-09-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20240917_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='api_article_slug_867b89_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['created_date'], name='api_article_created_1569a7_idx'),
        ),
    ]
