# Generated by Django 3.2.23 on 2024-09-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='joinNewsletter',
            field=models.BooleanField(default=False),
        ),
    ]
