# Generated by Django 3.2.23 on 2024-09-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_team_joinnewsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='joinNewsletter',
        ),
        migrations.AddField(
            model_name='customuser',
            name='joinNewsletter',
            field=models.BooleanField(default=False),
        ),
    ]
