# Generated by Django 3.2.23 on 2024-09-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_quizscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizscore',
            name='selected_answers',
            field=models.JSONField(default=dict),
        ),
    ]
