# Generated by Django 3.2.23 on 2024-09-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_quizscore_selected_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='reminders',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
