# Generated by Django 3.2.23 on 2024-10-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_calendarevent_reminders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
