# Generated by Django 3.2.23 on 2024-10-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_habit_reminder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
