# Generated by Django 3.2.23 on 2024-10-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_habit_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='canReview',
            field=models.BooleanField(default=False),
        ),
    ]
