# Generated by Django 3.2.23 on 2024-10-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_customuser_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='canReview',
            new_name='hasReview',
        ),
    ]
