# Generated by Django 3.2.23 on 2024-10-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_notes_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='sync_time',
            field=models.BooleanField(default=False),
        ),
    ]
