# Generated by Django 3.2.23 on 2024-10-12 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20241009_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevent',
            old_name='end_datetime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='calendarevent',
            old_name='start_datetime',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='event_title',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='is_shared',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='event_source',
            field=models.CharField(default='habits_us', max_length=50),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='summary',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='recurrence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='reminders',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='status',
            field=models.CharField(default='confirmed', max_length=50),
        ),
    ]
