# Generated by Django 3.2.23 on 2024-10-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20241012_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_day_of_month',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
